// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ete-wF_12tmvsDKEduaNOh2VqYmCqvU',
    appId: '1:876319586585:android:14c05f1fe38dbf6d3f2d88',
    messagingSenderId: '876319586585',
    projectId: 'ai-habit-agent',
    storageBucket: 'ai-habit-agent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXqgWtOS9WlWYT_LU0e-LbB2RGXjfouyg',
    appId: '1:876319586585:ios:0fc50ab92e16ede23f2d88',
    messagingSenderId: '876319586585',
    projectId: 'ai-habit-agent',
    storageBucket: 'ai-habit-agent.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXqgWtOS9WlWYT_LU0e-LbB2RGXjfouyg',
    appId: '1:876319586585:ios:0fc50ab92e16ede23f2d88',
    messagingSenderId: '876319586585',
    projectId: 'ai-habit-agent',
    storageBucket: 'ai-habit-agent.firebasestorage.app',
    iosBundleId: 'com.example.agentApp',
  );

}